// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyForWebPreview1234567890',
    appId: '1:101194866373:web:saykhtaxidemo',
    messagingSenderId: '101194866373',
    projectId: 'saykh-taxi-algeria',
    authDomain: 'saykh-taxi-algeria.firebaseapp.com',
    storageBucket: 'saykh-taxi-algeria.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyForAndroid1234567890',
    appId: '1:101194866373:android:saykhtaxi',
    messagingSenderId: '101194866373',
    projectId: 'saykh-taxi-algeria',
    storageBucket: 'saykh-taxi-algeria.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyForIos1234567890',
    appId: '1:101194866373:ios:saykhtaxi',
    messagingSenderId: '101194866373',
    projectId: 'saykh-taxi-algeria',
    storageBucket: 'saykh-taxi-algeria.appspot.com',
    iosBundleId: 'com.saykh.taxi',
  );
}
